server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: ${DB_USER}
    password: ${DB_PASSWORD}

#jpa configuration
  jpa:
    show-sql: true

#for creating and update schemas and tables
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web.exposure:
      include: "*"

app:
  message: "Hello Product!"
